"use client";

import { createContext, useState } from "react";

export const generateMetadata= {
  title: "Timeline | Keen Keeper",
  description: "Generated by create next app",
};
const FriendContext = createContext();

export const FriendsContextProvider = ({ children }) => {
  const [timeline, setTimeline] = useState([]);

  const addTimeline = (type, friend) => {
    const newItem = {
      id: Date.now(),
      type,
      name: friend.name,
      time: new Date().toLocaleTimeString(),
    };

    setTimeline((prev) => [newItem, ...prev]);
  };

  return (
    <FriendContext.Provider value={{ timeline, addTimeline }}>
      {children}
    </FriendContext.Provider>
  );
};

export default FriendContext;
